### PR TITLE
Replace anyhow with thiserror in library accessible areas

### PR DESCRIPTION
**Pull request by Fiono11**
Don't know why this isn't working.

### CODE REVIEW

**Comment by Fiono11** [comment]
This PR addresses issue #20 .

**Review by gak — APPROVED** [review]
Nice one 👍

**Comment by gak** [comment]
All good, just that cargo conflict. Probably should use main's version which I fixed.

Also maybe throw that test.wallet in .gitignore as it just gets generated in some of the tests.

**Comment by gak** [comment]
🎉

**Pull request merged**
